#!/usr/bin/python3

from sys import argv
import math

def factor():
    with open(argv[1]) as f:
        for line in f:
            num = int(line)
            print("{:d}=".format(num), end="")
            
            if num % 2 == 0:
                print("{}*2".format(num//2))
                continue
            
            sqn = int(math.sqrt(num))
            if sqn % 2 == 0:
                sqn += 1
            
            i = 3
            while i <= sqn:
                if num % i == 0:
                    print("{}*{}".format(i, num//i))
                    break
                i += 2
            else:
                print("{}={}*1".format(num, num))

factor()
