#!/usr/bin/python3

from sys import argv
from math import sqrt

"""

A module that Factorizes numbers from the input file into two prime factors.

"""


def factor():
    """
    Factorizes numbers from the input file into two prime factors.

    Reads numbers from the file specified in the command-line arguments
    and prints their prime factorization in the format
    "number=factor1*factor2".
    If the number is even, it is factorized as "number=2*factor".
    If the number is prime, it is factorized as "number=number*1".

    Command Line Usage:
        ./factors <input_file>
    """
    with open(argv[1]) as f:
        for line in f:
            num = int(line)
            print("{:d}=".format(num), end="")

            if num % 2 == 0:
                print("{}*2".format(num//2))
                continue

            sqn = int(sqrt(num))
            if sqn % 2 == 0:
                sqn += 1

            i = 3
            while i <= sqn and num % i != 0:
                i += 2

            if i <= sqn:
                factor1 = num // i
                factor2 = i
                print("{}*{}".format(factor1, factor2))
            else:
                print("{}={}*1".format(num, num))


if __name__ == "__main__":
    factor()
